name: 💡 Solicitud de función
about: Sugiere una idea para este proyecto.
title: "[FEATURE REQUEST] <title>"
labels: ["mejora"]
assignees: 'TeenBiscuits'
body:
  - type: input
    id: title
    attributes:
    label: La idea
    description: "Descripción breve de la idea que tienes para este proyecto"
    validations:
    required: true
  - type: input
    id: steps
    attributes:
    label: Cuéntame más
    description: "Explica tu idea"
    placeholder: "Explica en profundidad tu idea..."
    validations:
    required: false
