name: Construir documentación

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: docs/pro
  ARTIFACT: webHelpPRO2-all.zip
  # Writerside docker image version
  DOCKER_VERSION: 233.14272

jobs:
  construir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Construir documentación de Writerside usando Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
          retention-days: 7

  comprobar:
    # Requires build job results
    needs: construir
    runs-on: ubuntu-latest

    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Comprobar documentación
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

  publicar:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Requires the build job results
    needs: comprobar
    runs-on: ubuntu-latest
    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Descomprimir artefacto
        run: unzip -O UTF-8 -qq ${{ env.ARTIFACT }} -d dir

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Implementar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
