# SPDX-FileCopyrightText: 2024 Pablo Portas López <pablo.portas@udc.es>
#
# SPDX-License-Identifier: GPL-3.0-only AND MIT AND Apache-2.0

name: 🚀 Despliegue documentación

on:
  push:
    paths: ["docs/**"]
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: 'docs/pro'
  ARTIFACT: 'webHelpPRO2-all.zip'
  DOCKER_VERSION: '233.14938'
  ALGOLIA_ARTIFACT: 'algolia-indexes-PRO.zip'
  ALGOLIA_APP_NAME: '0K3UBN277V'
  ALGOLIA_INDEX_NAME: 'pro2324'
  ALGOLIA_KEY: '${{ secrets.ALGOLIA_KEY }}'
  CONFIG_JSON_PRODUCT: 'PRO'
  CONFIG_JSON_VERSION: '1.0'

jobs:
  construir:
    name: 📦 Construir
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repositorio
        # GitHub Actions
        # MIT
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: 🏗️ Construir con Writerside usando Docker
        # JetBrains Open Source
        # Apache-2.0
        # https://github.com/JetBrains/writerside-github-action
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: ⬆️ Subir artefacto con los resultados de la construcción
        uses: actions/upload-artifact@v3
        # GitHub Actions
        # MIT
        # https://github.com/actions/upload-artifact
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
            artifacts/${{ env.ALGOLIA_ARTIFACT }}
          retention-days: 7

  comprobar:
    name: 📊 Comprobar
    needs: construir
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Descargar artefactos
        # GitHub Actions
        # MIT
        # https://github.com/actions/download-artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: artifacts

      - name: 📊 Comprobar documentación
        # JetBrains Open Source
        # Apache-2.0
        # https://github.com/JetBrains/writerside-checker-action
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

  publicar:
    name: 🌐 Publicar Web
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [construir, comprobar]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Descargar artefacto
        # GitHub Actions
        # MIT
        # https://github.com/actions/download-artifact
        uses: actions/download-artifact@v3
        with:
          name: docs

      - name: 🗃️ Descomprimir artefacto
        run: unzip -O UTF-8 -qq '${{ env.ARTIFACT }}' -d dir

      - name: 🔎 Configurar IndexNow
        run: echo ${{ secrets.INDEXNOW_KEY }} > dir/${{ secrets.INDEXNOW_KEY }}.txt

      - name: 🔩 Configurar Pages
        uses: actions/configure-pages@v5

      - name: 📦 Empaquetar y subir artefacto de Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: 📖 Implementar en GitHub Pages
        # GitHub Actions
        # MIT
        # https://github.com/actions/deploy-pages
        id: deployment
        uses: actions/deploy-pages@v4

  publicar-indexes:
    name: 🔎 Publicar Indexes
    needs: [construir, comprobar, publicar]
    runs-on: ubuntu-latest
    # 
    container:
      image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:2.0.32-2
    steps:
      - name: ⬇️ Descargar artefacto
        # GitHub Actions
        # MIT
        # https://github.com/actions/download-artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
      - name: 🗃️ Descomprimir artefacto
        run: |
          unzip -O UTF-8 -qq '${{ env.ALGOLIA_ARTIFACT }}' -d algolia-indexes
          env algolia-key='${{env.ALGOLIA_KEY}}' java -jar /opt/builder/help-publication-agent.jar \
          update-index \
          --application-name '${{env.ALGOLIA_APP_NAME}}' \
          --index-name '${{env.ALGOLIA_INDEX_NAME}}' \
          --product '${{env.CONFIG_JSON_PRODUCT}}' \
          --version '${{env.CONFIG_JSON_VERSION}}' \
          --index-directory algolia-indexes/ \
          2>&1 | tee algolia-update-index-log.txt

  indexnow:
    needs: [construir, comprobar, publicar]
    name: 🔎 Publicar Sitemap
    runs-on: ubuntu-latest
    steps:
      - name: ⬆️ Subir Sitemap
        # Bojie Yang
        # MIT
        # https://github.com/bojieyang/indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://teenbiscuits.github.io/Pro2324/sitemap.xml' 
          key: ${{ secrets.INDEXNOW_KEY }}
          # endpoint: www.bing.com # Es el default
          failure-strategy: error
