# SPDX-FileCopyrightText: 2024 Pablo Portas López <pablo.portas@udc.es>
#
# SPDX-License-Identifier: GPL-3.0-only

name: Construir documentación

on:
  push:
    paths: ["docs/**"]
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: 'docs/pro'
  ARTIFACT: 'webHelpPRO2-all.zip'
  DOCKER_VERSION: '233.14389'
  ALGOLIA_ARTIFACT: 'algolia-indexes-PRO.zip'
  ALGOLIA_APP_NAME: '0K3UBN277V'
  ALGOLIA_INDEX_NAME: 'pro2324'
  ALGOLIA_KEY: '${{ secrets.ALGOLIA_KEY }}'
  CONFIG_JSON_PRODUCT: 'PRO'
  CONFIG_JSON_VERSION: '2023-2024'

jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Construir documentación de Writerside usando Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Subir artefacto con los resultados de la construcción
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
            artifacts/${{ env.ALGOLIA_ARTIFACT }}
          retention-days: 7

  comprobar:
    needs: construir
    runs-on: ubuntu-latest
    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Comprobar documentación
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

  publicar:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [construir, comprobar]
    runs-on: ubuntu-latest
    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Descomprimir artefacto
        run: unzip -O UTF-8 -qq '${{ env.ARTIFACT }}' -d dir

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Empaquetar y subir artefacto de Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Implementar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publicar-indexes:
    needs: [construir, comprobar, publicar]
    runs-on: ubuntu-latest
    container:
      image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:2.0.32-2
    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Unzip artefacto
        run: |
          unzip -O UTF-8 -qq '${{ env.ALGOLIA_ARTIFACT }}' -d algolia-indexes
          env algolia-key='${{env.ALGOLIA_KEY}}' java -jar /opt/builder/help-publication-agent.jar \
          update-index \
          --application-name '${{env.ALGOLIA_APP_NAME}}' \
          --index-name '${{env.ALGOLIA_INDEX_NAME}}' \
          --product '${{env.CONFIG_JSON_PRODUCT}}' \
          --version '${{env.CONFIG_JSON_VERSION}}' \
          --index-directory algolia-indexes/ \
          2>&1 | tee algolia-update-index-log.txt
