# SPDX-FileCopyrightText: 2024 Pablo Portas L贸pez <pablo.portas@udc.es>
#
# SPDX-License-Identifier: GPL-3.0-only

name: Comprobar documentaci贸n

on:
  pull_request:
    types:
      - opened
    paths:
      - 'docs/**'
    branches: ["main"]

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: docs/pro
  ARTIFACT: webHelpPRO2-all.zip
  # Writerside docker image version
  DOCKER_VERSION: 233.14389

jobs:
  construir:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Construir documentaci贸n de Writerside usando Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
          retention-days: 1

  comprobar:
    # Requires build job results
    needs: construir
    runs-on: ubuntu-latest

    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Comprobar documentaci贸n
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

