# SPDX-FileCopyrightText: 2024 Pablo Portas López <pablo.portas@udc.es>
#
# SPDX-License-Identifier: GPL-3.0-only

name: Comprobar documentación

on:
  pull_request:
    types: ["opened"]
    paths: ["docs/**"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: 'docs/pro'
  ARTIFACT: 'webHelpPRO2-all.zip'
  DOCKER_VERSION: '233.14938'
  ALGOLIA_ARTIFACT: 'algolia-indexes-PRO.zip'
  ALGOLIA_APP_NAME: '0K3UBN277V'
  ALGOLIA_INDEX_NAME: 'pro2324'
  ALGOLIA_KEY: '${{ secrets.ALGOLIA_KEY }}'
  CONFIG_JSON_PRODUCT: 'PRO'
  CONFIG_JSON_VERSION: '1.0'

jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Construir documentación de Writerside usando Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Subir artefacto con los resultados de la construcción
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
            artifacts/${{ env.ALGOLIA_ARTIFACT }}
          retention-days: 7

  comprobar:
    needs: construir
    runs-on: ubuntu-latest
    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: artifacts

      - name: Comprobar documentación
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

